# Generated by Django 4.0.4 on 2022-06-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='IdCliente')),
                ('nombreCliente', models.CharField(max_length=50, verbose_name='NombreCliente')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('comuna', models.CharField(max_length=50, verbose_name='Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='IdProducto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='NombreProducto')),
            ],
        ),
    ]
