# Generated by Django 4.0.4 on 2022-06-28 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Correo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Direccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default=django.utils.timezone.now, max_length=8, verbose_name='Telefono'),
            preserve_default=False,
        ),
    ]
