# Generated by Django 4.0.4 on 2022-07-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idCliente',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='IdCliente'),
        ),
    ]
