# Generated by Django 4.0.4 on 2022-07-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_producto_imagen_alter_cliente_idcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombreCliente',
            field=models.TextField(max_length=50, verbose_name='NombreCliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.PositiveIntegerField(verbose_name='Telefono'),
        ),
    ]
