# Generated by Django 4.0.4 on 2022-07-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_producto_precioproducto_producto_stockproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idCliente',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombreCliente',
            field=models.CharField(max_length=50, verbose_name='NombreCliente'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='descripcion', max_length=100, verbose_name='Descripcion'),
        ),
    ]
