# Generated by Django 4.0.4 on 2022-07-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_cliente_idcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=100, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioProducto',
            field=models.PositiveIntegerField(verbose_name='PrecioProducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stockProducto',
            field=models.PositiveIntegerField(verbose_name='StockProducto'),
        ),
    ]
