# Generated by Django 4.0.4 on 2022-07-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precioProducto',
            field=models.PositiveIntegerField(default='0000', verbose_name='PrecioProducto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stockProducto',
            field=models.PositiveIntegerField(default='0000', verbose_name='StockProducto'),
        ),
    ]
